# Getting started

::: {#chapter-02-summary .callout-important .unnumbered title="Summary" appearance="simple" icon="false"}
This is a long chapter that goes on a whistle stop tour of R.

It covers setting up RStudio, installing packages, finding help, how to organise a project, the atoms of R and how they combine in useful ways. By the end you'll be able to create a plot and write outputs using the Palmer Penguins package.

Don't worry if you don't get it all in the first pass, that's why the book and lots of other materials exist, so you can come back here or explore out there.
:::

## What is R?

Stuff

## RStudio

### What is real?

### Where am I?

## Installing and loading packages

## What is a function and how do I use them?

## A project orientated workflow

## Base R, the tidyverse and tidy data

## Atoms of R

## Categorical data aka Factors

## Assigning objects

### Indexing and sub-setting

## Data containers: Lists, matrices, arrays and data frames

## Plotting and exporting data

## Getting help

https://rweekly.org/ https://posit.cloud/learn/recipes https://www.bigbookofr.com/
