project:
  output-dir: .

format: 
  revealjs:
    theme: [my-styles.scss] 
    embed-resources: true
    #chalkboard: 
     # buttons: false
title-slide-attributes:
    #data-background-image: img/USH0149_LOGO-2021_RGB_White_Punched-AW.png
    #data-background-size: 25%
    #data-background-position: top right
    data-background-color: "#8D3970"
