---
title: "Read excel practice"
---

```{r}
library(tidyverse)
library(janitor)
library(readxl)
```

## Read in

> "...a fortnightly check that Stephie carries out for REF and Funder Compliance, the Export Control Team periodically asks us for information about particular staff/institutions/countries and we can use this as it has been sense checked as UoS, trying to search in the Affiliations can be very time consuming..."

```{r}
dat <- read_xlsx("../data/V1 New OA Compliance Master Sheet.xlsx", sheet = "Master (New data)")
```

```{r}
dat |> filter(`UoS Corresponding Author` == "Yes") |> tally()

dt <- dat |> #select(Affiliations) |> 
  separate_wider_delim(cols = Affiliations, delim = ";", names_sep = "_", 
                       too_few = "align_start",too_many = "drop") |> 
  select(14:827) |> 
  #mutate(uos = coalesce(Affiliations_1,Affiliations_2))
  mutate(across(starts_with("Affiliations"), str_extract, "Southampton", 
         .names = "{.col}_extract")) |> 
  mutate(component = coalesce(ends_with("_extract")),
        .keep = "unused")

# dat |> group_by(`Document Type`) |> summarise(n())
# 
# dat |> mutate(uos_aff = str_extract(Affiliations, "(?<=;)(.*Southampton.*)(?=;)")) |> view()
```
